### ISSUE TITLE
parsing failure?

### ISSUE THREAD

**Issue by mircealungu** [Perlten/MT-diagrams#17]
in the case of zeeguu, with the config:

```
{
    "$schema": "https://raw.githubusercontent.com/Perlten/MT-diagrams/master/config.schema.json",
    "name": "zeeguu",
    "rootFolder": "zeeguu",
    "github": {
        "url": "",
        "branch": "main"
    },
    "saveLocation": "./diagrams/",
    "views": {
        "completeView": {
            "packages": [],
            "ignorePackages": ["test"]
        }
    }
}
```

although there's a dependency from exercises to word_stats 

<img width="664" alt="image" src="https://user-images.githubusercontent.com/464519/221807992-60b3fae9-2c25-40eb-a769-91291cb93b1f.png">

this one is not present in the model:

<img width="771" alt="image" src="https://user-images.githubusercontent.com/464519/221808439-4de74d78-b4fd-4a4c-b49d-cc18b24354d1.png">

as you can see, the two packages are not connected. 

why would that be?

**Comment by Perlten** [comment]
We did consider code written inside __init__.py files. That has now been fixed :)
